/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rjrak
 */
public class screen2 extends javax.swing.JFrame {

    /**
     * Creates new form screen2
     */
    public long acc1=0;
    public String email="";
    public int flag=0;
    public long otp=0;
    public screen2(){
        initComponents();
    }
    public screen2(long acc) {
        initComponents();
        acc1=acc;
        jTextField2.setVisible(false);
        jLabel9.setVisible(false);
        jButton4.setVisible(false);
        
        try{
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","rakshit");
        Statement st= con.createStatement();
        PreparedStatement stmt= con.prepareStatement("SELECT * FROM KYC WHERE ACCNO=?",ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
        stmt.setLong(1, acc);
        ResultSet rs=stmt.executeQuery();
        rs.absolute(1);
        jLabel1.setText("Hey! "+rs.getString("NAME"));
        jLabel3.setText("A/C NO: "+rs.getLong("ACCNO"));
        jLabel4.setText("AADHAAR: "+rs.getLong("AADHAAR"));
        jLabel5.setText("EMAIL: "+rs.getString("EMAIL"));
        jLabel6.setText("RMN: "+rs.getLong("REG_MOB"));
        email=rs.getString("EMAIL");
        stmt= con.prepareStatement("SELECT * FROM ACC_DET WHERE ACCNO=?",ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
        stmt.setLong(1, acc);
        rs=stmt.executeQuery();
        rs.absolute(1);
        jLabel7.setText("BALANCE: RS."+rs.getDouble("BAL"));
        con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);    
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Book", 1, 72)); // NOI18N
        jLabel2.setText("VIT NET-BANKING");

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Book", 1, 48)); // NOI18N
        jLabel1.setText("Hey!!");

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Book", 1, 30)); // NOI18N
        jLabel3.setText("A/C NO:");

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Book", 1, 30)); // NOI18N
        jLabel4.setText("AADHAAR:");

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Book", 1, 30)); // NOI18N
        jLabel5.setText("EMAIL:");

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Book", 1, 30)); // NOI18N
        jLabel6.setText("RMN:");

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Book", 1, 36)); // NOI18N
        jLabel7.setText("BALANCE:");

        jButton1.setFont(new java.awt.Font("Franklin Gothic Book", 1, 36)); // NOI18N
        jButton1.setText("UPDATE PROFILE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Franklin Gothic Book", 1, 36)); // NOI18N
        jButton2.setText("WITHDRAWL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Franklin Gothic Book", 1, 36)); // NOI18N
        jButton3.setText("DEPOSIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Book", 1, 36)); // NOI18N
        jLabel8.setText("AMOUNT");

        jTextField1.setFont(new java.awt.Font("Franklin Gothic Book", 1, 30)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Book", 1, 36)); // NOI18N
        jLabel9.setText("OTP");

        jTextField2.setFont(new java.awt.Font("Franklin Gothic Book", 1, 30)); // NOI18N

        jButton4.setFont(new java.awt.Font("Franklin Gothic Book", 1, 30)); // NOI18N
        jButton4.setText("VERIFY");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Franklin Gothic Book", 1, 36)); // NOI18N
        jButton5.setText("LOGOUT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 425, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(51, 51, 51)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(336, 336, 336)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String amountt=jTextField1.getText();
        double amount=Double.parseDouble(amountt);
        if(jTextField1.getText().isEmpty()==false){
        jTextField2.setVisible(true);
        jButton4.setVisible(true);
        jLabel9.setVisible(true);
        flag=1;
        otp=new Banking().SendMailbySite(email);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(flag==1 && Long.parseLong(jTextField2.getText())==otp){
            try{
                String amountt=jTextField1.getText();
                double amount=Double.parseDouble(amountt);
        
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","rakshit");
                Statement st= con.createStatement();
                PreparedStatement stmt=con.prepareStatement("SELECT * FROM ACC_DET WHERE ACCNO=?",ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
                stmt.setLong(1, acc1);
                ResultSet rs=stmt.executeQuery();
                rs.absolute(1);
                
                stmt=con.prepareStatement("INSERT INTO ACC_DET_FULL(ACCNO,CREDIT,DEBIT,BAL,DT_TRANS) VALUES (?,?,?,?,TO_CHAR(TRUNC(SYSDATE),'DD/MM/YYYY'))",ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
                stmt.setLong(1,acc1);
                stmt.setDouble(2,amount);
                stmt.setDouble(3,0.0);
                stmt.setDouble(4,rs.getDouble("BAL")+amount);
                stmt.executeUpdate();
                
                stmt=con.prepareStatement("UPDATE ACC_DET SET BAL=? WHERE ACCNO=?",ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
                stmt.setLong(2, acc1);
                stmt.setDouble(1, rs.getDouble("BAL")+amount);
                stmt.executeUpdate();
        
                 con.close();
                JOptionPane.showMessageDialog(null, "Successfully Deposited");
                new screen2(acc1).setVisible(true);
                dispose();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else if(flag==2 && Long.parseLong(jTextField2.getText())==otp){
            try{
                String amountt=jTextField1.getText();
                double amount=Double.parseDouble(amountt);
        
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","rakshit");
                Statement st= con.createStatement();
                PreparedStatement stmt=con.prepareStatement("SELECT * FROM ACC_DET WHERE ACCNO=?",ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
                stmt.setLong(1, acc1);
                ResultSet rs=stmt.executeQuery();
                rs.absolute(1);
                
                stmt=con.prepareStatement("INSERT INTO ACC_DET_FULL(ACCNO,CREDIT,DEBIT,BAL,DT_TRANS) VALUES (?,?,?,?,TO_CHAR(TRUNC(SYSDATE),'DD/MM/YYYY'))",ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
                stmt.setLong(1,acc1);
                stmt.setDouble(2,0.0);
                stmt.setDouble(3,amount);
                stmt.setDouble(4,rs.getDouble("BAL")-amount);
                stmt.executeUpdate();
                
                stmt=con.prepareStatement("UPDATE ACC_DET SET BAL=? WHERE ACCNO=?",ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
                stmt.setLong(2, acc1);
                stmt.setDouble(1, rs.getDouble("BAL")-amount);
                stmt.executeUpdate();
        
                 con.close();
                JOptionPane.showMessageDialog(null, "Successfully Withdrawn");
                new screen2(acc1).setVisible(true);
                dispose();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String amountt=jTextField1.getText();
        double amount=Double.parseDouble(amountt);
        if(jTextField1.getText().isEmpty()==false){
        try{
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","rakshit");
        Statement st= con.createStatement();
        PreparedStatement stmt= con.prepareStatement("SELECT * FROM ACC_DET WHERE ACCNO=?",ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
        stmt.setLong(1, acc1);
        ResultSet rs=stmt.executeQuery();
        rs.absolute(1);
        if(rs.getDouble("BAL")>=amount){
            jTextField2.setVisible(true);
            jLabel9.setVisible(true);
            jButton4.setVisible(true);
            flag=2;
            otp=new Banking().SendMailbySite(email);
        }
        con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);    
        }
        
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new page1().setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(screen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(screen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(screen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(screen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new screen2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
